### ISSUE TITLE
Sometimes a tag is added two times.

### ISSUE THREAD

**Issue by Abdulsametileri** [JohMun/vue-tags-input#29] opened 2018-08-11 19:00 UTC
I really sure about my code. 

                        <vue-tags-input
                        :id="'vtg' + index"
                        style="max-width: none; width: 100%;"
                        v-model="form.parent_id[index]"
                        :tags="Ayet.Tags"
                        placeholder="Konu Ekle"
                        :autocomplete-items="filteredItems(index)"
                        :avoid-adding-duplicates="true"
                        @before-adding-tag="handler => addingTag(handler, Ayet) "
                        @before-deleting-tag="handler => deletingTag(handler, Ayet)"
                        @tags-changed="newTags => Ayet.Tags = newTags"  

despite I use avoid-adding-duplicates. handler.addTag(); is invoked twice. I can not understand why it works like that 

```
addingTag(handler: any, Ayet: Object) {
      handler.addTag();
},

```
![screen shot 2018-08-11 at 9 59 15 pm](https://user-images.githubusercontent.com/19360039/43995166-db337e52-9db1-11e8-84ee-5e129f00d769.png)

here it is. When ı add asdasd, it is added twice. Where is the problem?

**Comment by JohMun** [comment] 2018-08-12 13:47
I can't reproduce that issue. Can you please create a [codepen](https://codepen.io/), so I can exactly see how you use vue-tags-input?

**Comment by Abdulsametileri** [comment] 2018-08-12 16:58
My project complexity is too much. So ı really debug my code but still ı have not found error cause it this behaviour

**Comment by JohMun** [comment] 2018-10-04 16:48
Sorry, I could not reproduce the issue. I close it now.

**Closed by JohMun** 2018-10-04 16:48 UTC
